name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
        - antra-profolio
  pull_request:
    branches:
        - antra-profolio
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
            repoToken: '${{ secrets.GITHUB_TOKEN }}'
            firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEWISLUU }}'
            projectId: lewisluu
            channelID : live
            target: lucasluu
        env:
            FIREBASE_CLI_EXPERIMENTS: webframeworks
